#!/usr/bin/env bash
#Configure Nginx server so that it prints includes a custome header directive

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/sendfile on;/a error_page 404 /error_404.html;' /etc/nginx/nginx.conf
sudo sed -i '/sendfile on;/a add_header X-Served-By $hostname always;' /etc/nginx/nginx.conf
sudo service nginx restart
