#!/usr/bin/env bash
# display contents of /etc/passwd as a
# username(0) user id(2) home directory(5)

FILENAME="/etc/passwd" 
while IFS=":" read -r name pswd uid gid gecos hmdir shell; do
	echo "The user $name is part of the $gid gang, lives in $hmdir and rides $shell. $uid's place is protected by the passcode $pswd, more info about the user here: $gecos"
done < "$FILENAME"
