#!/usr/bin/env bash
# Display "Best School" 10 times using while loop
# on the 9th iteration also display "Hi"
i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
