#!/usr/bin/env bash
# Display "Best School" 10 times using while loop
# on the 4th iteration also display "bad luck"
# on the 8th iteration also display "good luck"
i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
