#!/usr/bin/env bash
# display hours from 0 to 12 and minutes from 1 to 59

hour=0
minute=1

while [ $hour -lt 13 ]; do
	echo "Hour: $hour"
	while [ $minute -lt 60 ]; do
		echo "$minute"
		(( minute++ ))
	done
	minute=1
	(( hour++ ))
done
