#!/usr/bin/env bash
#install ufw and configure it block all conncetions except
# ssh, http and https

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
