#!/usr/bin/env bash
#modify the /etc/hosts file

file="/etc/hosts"

cp "$file" ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '/^127.0.0.*/a 8.8.8.8\tfacebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
